// ==UserScript==
// @name         Paywall Remover
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  Remove paywalls by redirecting to removepaywall.com
// @author       Ro'sø
//
// @match        https://removepaywall.com*
//
// @match        https://*.360dx.com/*/*
// @match        https://*.aamulehti.fi/*/*
// @match        https://*.abc.es/*/*
// @match        https://*.abendblatt.de/*/*
// @match        https://*.adage.com/*/*
// @match        https://*.adelaidenow.com.au/*/*
// @match        https://*.adweek.com/*/*
// @match        https://*.afr.com/*/*
// @match        https://*.aftonbladet.se/*/*
// @match        https://*.aisnenouvelle.fr/*/*
// @match        https://*.ajc.com/*/*
// @match        https://*.al.com/*/*
// @match        https://*.allgaeuer-zeitung.de/*/*
// @match        https://*.alternatives-economiques.fr/*/*
// @match        https://*.ambito.com/*/*
// @match        https://*.americanaffairsjournal.org/*/*
// @match        https://*.americanbanker.com/*/*
// @match        https://*.apollo-magazine.com/*/*
// @match        https://*.ara.cat/*/*
// @match        https://*.arabalears.cat/*/*
// @match        https://*.artnet.com/*/*
// @match        https://*.arvopaperi.fi/*/*
// @match        https://*.asia.nikkei.com/*/*
// @match        https://*.asiatimes.com/*/*
// @match        https://*.atlantico.fr/*/*
// @match        https://*.augsburger-allgemeine.de/*/*
// @match        https://*.automobilwoche.de/*/*
// @match        https://*.autonews.com/*/*
// @match        https://*.azcentral.com/*/*
// @match        https://*.backpacker.com/*/*
// @match        https://*.baltimoresun.com/*/*
// @match        https://*.barrons.com/*/*
// @match        https://*.belfasttelegraph.co.uk/*/*
// @match        https://*.bendigoadvertiser.com.au/*/*
// @match        https://*.berliner-zeitung.de/*/*
// @match        https://*.berlingske.dk/*/*
// @match        https://*.betamtb.com/*/*
// @match        https://*.betternutrition.com/*/*
// @match        https://*.betterprogramming.pub/*/*
// @match        https://*.bicycling.com/*/*
// @match        https://*.bienpublic.com/*/*
// @match        https://*.billboard.com/*/*
// @match        https://*.bizjournals.com/*/*
// @match        https://*.bloomberg.com/*/*
// @match        https://*.bloombergquint.com/*/*
// @match        https://*.bnd.com/*/*
// @match        https://*.bnn.de/*/*
// @match        https://*.bonappetit.com/*/*
// @match        https://*.bordermail.com.au/*/*
// @match        https://*.bostonglobe.com/*/*
// @match        https://*.braunschweiger-zeitung.de/*/*
// @match        https://*.brisbanetimes.com.au/*/*
// @match        https://*.britannica.com/*/*
// @match        https://*.buffalonews.com/*/*
// @match        https://*.business-standard.com/*/*
// @match        https://*.businessinsider.com/*/*
// @match        https://*.businessoffashion.com/*/*
// @match        https://*.cairnspost.com.au/*/*
// @match        https://*.calgaryherald.com/*/*
// @match        https://*.canberratimes.com.au/*/*
// @match        https://*.capitalgazette.com/*/*
// @match        https://*.causeur.fr/*/*
// @match        https://*.cen.acs.org/*/*
// @match        https://*.centralwesterndaily.com.au/*/*
// @match        https://*.centrepresseaveyron.fr/*/*
// @match        https://*.challenges.fr/*/*
// @match        https://*.charentelibre.fr/*/*
// @match        https://*.charliehebdo.fr/*/*
// @match        https://*.charlotteobserver.com/*/*
// @match        https://*.chicagobusiness.com/*/*
// @match        https://*.chicagotribune.com/*/*
// @match        https://*.chronicle.com/*/*
// @match        https://*.cicero.de/*/*
// @match        https://*.clarin.com/*/*
// @match        https://*.cleaneatingmag.com/*/*
// @match        https://*.cleveland.com/*/*
// @match        https://*.climbing.com/*/*
// @match        https://*.cmjornal.pt/*/*
// @match        https://*.codesports.com.au/*/*
// @match        https://*.commentary.org/*/*
// @match        https://*.connaissancedesarts.com/*/*
// @match        https://*.corriere.it/*/*
// @match        https://*.corriereadriatico.it/*/*
// @match        https://*.corrieredellosport.it/*/*
// @match        https://*.cosmopolitan.com/*/*
// @match        https://*.countryliving.com/*/*
// @match        https://*.courant.com/*/*
// @match        https://*.courier-journal.com/*/*
// @match        https://*.couriermail.com.au/*/*
// @match        https://*.courrier-picard.fr/*/*
// @match        https://*.crainscleveland.com/*/*
// @match        https://*.crainsdetroit.com/*/*
// @match        https://*.crainsnewyork.com/*/*
// @match        https://*.csmonitor.com/*/*
// @match        https://*.curbed.com/*/*
// @match        https://*.cw.com.tw/*/*
// @match        https://*.cyclingtips.com/*/*
// @match        https://*.dailyadvertiser.com.au/*/*
// @match        https://*.dailyliberal.com.au/*/*
// @match        https://*.dailypress.com/*/*
// @match        https://*.dailytelegraph.com.au/*/*
// @match        https://*.dailywire.com/*/*
// @match        https://*.dallasnews.com/*/*
// @match        https://*.darkreading.com/*/*
// @match        https://*.demorgen.be/*/*
// @match        https://*.denverpost.com/*/*
// @match        https://*.detroitnews.com/*/*
// @match        https://*.deutsche-wirtschafts-nachrichten.de/*/*
// @match        https://*.df.cl/*/*
// @match        https://*.di.se/*/*
// @match        https://*.diariocorreo.pe/*/*
// @match        https://*.diariodemallorca.es/*/*
// @match        https://*.diariosur.es/*/*
// @match        https://*.diariovasco.com/*/*
// @match        https://*.digiday.com/*/*
// @match        https://*.digital.elmercurio.com/*/*
// @match        https://*.digital.lasegunda.com/*/*
// @match        https://*.discovermagazine.com/*/*
// @match        https://*.dn.se/*/*
// @match        https://*.dna.fr/*/*
// @match        https://*.dvhn.nl/*/*
// @match        https://*.eastbaytimes.com/*/*
// @match        https://*.eastwest.eu/*/*
// @match        https://*.economictimes.indiatimes.com/*/*
// @match        https://*.economist.com/*/*
// @match        https://*.editorialedomani.it/*/*
// @match        https://*.elcomercio.es/*/*
// @match        https://*.elcomercio.pe/*/*
// @match        https://*.elconfidencial.com/*/*
// @match        https://*.elcorreo.com/*/*
// @match        https://*.eldia.es/*/*
// @match        https://*.eldiario.es/*/*
// @match        https://*.eldiariomontanes.es/*/*
// @match        https://*.elespanol.com/*/*
// @match        https://*.elespectador.com/*/*
// @match        https://*.elle.com/*/*
// @match        https://*.elle.fr/*/*
// @match        https://*.elmundo.es/*/*
// @match        https://*.elnortedecastilla.es/*/*
// @match        https://*.elpais.com/*/*
// @match        https://*.elperiodico.com/*/*
// @match        https://*.eltiempo.com/*/*
// @match        https://*.enotes.com/*/*
// @match        https://*.entrepreneur.com/*/*
// @match        https://*.epe.es/*/*
// @match        https://*.espn.com/*/*
// @match        https://*.esprit.presse.fr/*/*
// @match        https://*.esquire.com/*/*
// @match        https://*.estadao.com.br/*/*
// @match        https://*.estrepublicain.fr/*/*
// @match        https://*.euobserver.com/*/*
// @match        https://*.eurekareport.com.au/*/*
// @match        https://*.exame.com/*/*
// @match        https://*.examiner.com.au/*/*
// @match        https://*.expansion.com/*/*
// @match        https://*.expressnews.com/*/*
// @match        https://*.farodevigo.es/*/*
// @match        https://*.faz.net/*/*
// @match        https://*.fd.nl/*/*
// @match        https://*.finance.si/*/*
// @match        https://*.financialexpress.com/*/*
// @match        https://*.financialpost.com/*/*
// @match        https://*.firstthings.com/*/*
// @match        https://*.fnlondon.com/*/*
// @match        https://*.folha.uol.com.br/*/*
// @match        https://*.forbes.com/*/*
// @match        https://*.foreignaffairs.com/*/*
// @match        https://*.foreignpolicy.com/*/*
// @match        https://*.fortune.com/*/*
// @match        https://*.franc-tireur.fr/*/*
// @match        https://*.freep.com/*/*
// @match        https://*.freiepresse.de/*/*
// @match        https://*.fresnobee.com/*/*
// @match        https://*.ft.com/*/*
// @match        https://*.ftm.nl/*/*
// @match        https://*.geelongadvertiser.com.au/*/*
// @match        https://*.genomeweb.com/*/*
// @match        https://*.gestion.pe/*/*
// @match        https://*.glassdoor.com/*/*
// @match        https://*.globes.co.il/*/*
// @match        https://*.goldcoastbulletin.com.au/*/*
// @match        https://*.goodhousekeeping.com/*/*
// @match        https://*.gooieneemlander.nl/*/*
// @match        https://*.gq.com/*/*
// @match        https://*.griffithreview.com/*/*
// @match        https://*.groene.nl/*/*
// @match        https://*.grubstreet.com/*/*
// @match        https://*.grupoabril.com.br/*/*
// @match        https://*.gva.be/*/*
// @match        https://*.gymclimber.com/*/*
// @match        https://*.haaretz.co.il/*/*
// @match        https://*.haaretz.com/*/*
// @match        https://*.haarlemsdagblad.nl/*/*
// @match        https://*.handelsblatt.com/*/*
// @match        https://*.harpers.org/*/*
// @match        https://*.haz.de/*/*
// @match        https://*.hbr.org/*/*
// @match        https://*.hbrchina.org/*/*
// @match        https://*.hbvl.be/*/*
// @match        https://*.heraldsun.com.au/*/*
// @match        https://*.hilltimes.com/*/*
// @match        https://*.hindustantimes.com/*/*
// @match        https://*.historyextra.com/*/*
// @match        https://*.hollywoodreporter.com/*/*
// @match        https://*.housebeautiful.com/*/*
// @match        https://*.houstonchronicle.com/*/*
// @match        https://*.hoy.es/*/*
// @match        https://*.hs.fi/*/*
// @match        https://*.huffingtonpost.it/*/*
// @match        https://*.humo.be/*/*
// @match        https://*.ideal.es/*/*
// @match        https://*.ijmuidercourant.nl/*/*
// @match        https://*.ilfattoquotidiano.it/*/*
// @match        https://*.ilfoglio.it/*/*
// @match        https://*.ilgazzettino.it/*/*
// @match        https://*.ilgiorno.it/*/*
// @match        https://*.illawarramercury.com.au/*/*
// @match        https://*.ilmattino.it/*/*
// @match        https://*.ilmessaggero.it/*/*
// @match        https://*.ilrestodelcarlino.it/*/*
// @match        https://*.ilsecoloxix.it/*/*
// @match        https://*.iltalehti.fi/*/*
// @match        https://*.iltelegrafolivorno.it/*/*
// @match        https://*.inc.com/*/*
// @match        https://*.inc42.com/*/*
// @match        https://*.independent.co.uk/*/*
// @match        https://*.independent.ie/*/*
// @match        https://*.indianexpress.com/*/*
// @match        https://*.indiatoday.in/*/*
// @match        https://*.indystar.com/*/*
// @match        https://*.informacion.es/*/*
// @match        https://*.infzm.com/*/*
// @match        https://*.inkl.com/*/*
// @match        https://*.inquirer.com/*/*
// @match        https://*.intelligentinvestor.com.au/*/*
// @match        https://*.internazionale.it/*/*
// @match        https://*.intrafish.com/*/*
// @match        https://*.investorschronicle.co.uk/*/*
// @match        https://*.ipolitics.ca/*/*
// @match        https://*.italian.tech/*/*
// @match        https://*.italiaoggi.it/*/*
// @match        https://*.journaldunet.com/*/*
// @match        https://*.journalnow.com/*/*
// @match        https://*.jpost.com/*/*
// @match        https://*.jsonline.com/*/*
// @match        https://*.kansas.com/*/*
// @match        https://*.kansascity.com/*/*
// @match        https://*.kauppalehti.fi/*/*
// @match        https://*.kentucky.com/*/*
// @match        https://*.kn-online.de/*/*
// @match        https://*.knack.be/*/*
// @match        https://*.krautreporter.de/*/*
// @match        https://*.ksta.de/*/*
// @match        https://*.kurier.at/*/*
// @match        https://*.la-croix.com/*/*
// @match        https://*.labusinessjournal.com/*/*
// @match        https://*.ladepeche.fr/*/*
// @match        https://*.lalibre.be/*/*
// @match        https://*.lalsace.fr/*/*
// @match        https://*.lamontagne.fr/*/*
// @match        https://*.lanacion.com.ar/*/*
// @match        https://*.lanazione.it/*/*
// @match        https://*.lanouvellerepublique.fr/*/*
// @match        https://*.lanuovasardegna.it/*/*
// @match        https://*.laprovincia.es/*/*
// @match        https://*.lardennais.fr/*/*
// @match        https://*.larepubliquedespyrenees.fr/*/*
// @match        https://*.larioja.com/*/*
// @match        https://*.lasprovincias.es/*/*
// @match        https://*.lastampa.it/*/*
// @match        https://*.latercera.com/*/*
// @match        https://*.latimes.com/*/*
// @match        https://*.latribune.fr/*/*
// @match        https://*.lavanguardia.com/*/*
// @match        https://*.laverdad.es/*/*
// @match        https://*.lavie.fr/*/*
// @match        https://*.lavoixdunord.fr/*/*
// @match        https://*.lavozdigital.es/*/*
// @match        https://*.law.com/*/*
// @match        https://*.law360.com/*/*
// @match        https://*.lc.nl/*/*
// @match        https://*.lecho.be/*/*
// @match        https://*.ledauphine.com/*/*
// @match        https://*.ledevoir.com/*/*
// @match        https://*.lehighvalleylive.com/*/*
// @match        https://*.leidschdagblad.nl/*/*
// @match        https://*.lejdd.fr/*/*
// @match        https://*.lejsl.com/*/*
// @match        https://*.lenouveleconomiste.fr/*/*
// @match        https://*.leparisien.fr/*/*
// @match        https://*.leprogres.fr/*/*
// @match        https://*.lequipe.fr/*/*
// @match        https://*.lescienze.it/*/*
// @match        https://*.lesechos.fr/*/*
// @match        https://*.lesinrocks.com/*/*
// @match        https://*.lesoir.be/*/*
// @match        https://*.lest-eclair.fr/*/*
// @match        https://*.letelegramme.fr/*/*
// @match        https://*.levante-emv.com/*/*
// @match        https://*.levif.be/*/*
// @match        https://*.lexpress.fr/*/*
// @match        https://*.liberation-champagne.fr/*/*
// @match        https://*.limesonline.com/*/*
// @match        https://*.lindependant.fr/*/*
// @match        https://*.livelaw.in/*/*
// @match        https://*.livemint.com/*/*
// @match        https://*.ln-online.de/*/*
// @match        https://*.lne.es/*/*
// @match        https://*.loebclassics.com/*/*
// @match        https://*.loeildelaphotographie.com/*/*
// @match        https://*.lopinion.fr/*/*
// @match        https://*.lrb.co.uk/*/*
// @match        https://*.lunion.fr/*/*
// @match        https://*.lvz.de/*/*
// @match        https://*.magazine.atavist.com/*/*
// @match        https://*.mainichi.jp/*/*
// @match        https://*.mallorcazeitung.es/*/*
// @match        https://*.marca.com/*/*
// @match        https://*.marianne.net/*/*
// @match        https://*.marketwatch.com/*/*
// @match        https://*.marmai.fi/*/*
// @match        https://*.masslive.com/*/*
// @match        https://*.maz-online.de/*/*
// @match        https://*.mcall.com/*/*
// @match        https://*.medianama.com/*/*
// @match        https://*.medium.com/*/*
// @match        https://*.mediuutiset.fi/*/*
// @match        https://*.menshealth.com/*/*
// @match        https://*.mercurynews.com/*/*
// @match        https://*.mexiconewsdaily.com/*/*
// @match        https://*.miamiherald.com/*/*
// @match        https://*.mid-day.com/*/*
// @match        https://*.midi-olympique.fr/*/*
// @match        https://*.midilibre.fr/*/*
// @match        https://*.mikrobitti.fi/*/*
// @match        https://*.mlive.com/*/*
// @match        https://*.modernhealthcare.com/*/*
// @match        https://*.monacomatin.mc/*/*
// @match        https://*.morgenpost.de/*/*
// @match        https://*.muensterschezeitung.de/*/*
// @match        https://*.mv-voice.com/*/*
// @match        https://*.mz.de/*/*
// @match        https://*.nation.africa/*/*
// @match        https://*.nationalgeographic.com/*/*
// @match        https://*.nationalpost.com/*/*
// @match        https://*.nationalreview.com/*/*
// @match        https://*.nautil.us/*/*
// @match        https://*.neuepresse.de/*/*
// @match        https://*.newcastleherald.com.au/*/*
// @match        https://*.newleftreview.org/*/*
// @match        https://*.newrepublic.com/*/*
// @match        https://*.newsday.com/*/*
// @match        https://*.newsobserver.com/*/*
// @match        https://*.newstatesman.com/*/*
// @match        https://*.newsweek.com/*/*
// @match        https://*.newyorker.com/*/*
// @match        https://*.niagarafallsreview.ca/*/*
// @match        https://*.nicematin.com/*/*
// @match        https://*.nieuwsblad.be/*/*
// @match        https://*.nj.com/*/*
// @match        https://*.nl.nl/*/*
// @match        https://*.nn.de/*/*
// @match        https://*.nola.com/*/*
// @match        https://*.noordhollandsdagblad.nl/*/*
// @match        https://*.nordeclair.fr/*/*
// @match        https://*.nordlittoral.fr/*/*
// @match        https://*.northerndailyleader.com.au/*/*
// @match        https://*.northjersey.com/*/*
// @match        https://*.nouvelobs.com/*/*
// @match        https://*.noz.de/*/*
// @match        https://*.nrc.nl/*/*
// @match        https://*.nrpyrenees.fr/*/*
// @match        https://*.nrz.de/*/*
// @match        https://*.ntnews.com.au/*/*
// @match        https://*.nwzonline.de/*/*
// @match        https://*.nybooks.com/*/*
// @match        https://*.nydailynews.com/*/*
// @match        https://*.nymag.com/*/*
// @match        https://*.nyteknik.se/*/*
// @match        https://*.nytimes.com/*/*/*
// @match        https://*.nzherald.co.nz/*/*
// @match        https://*.nzz.ch/*/*
// @match        https://*.observador.pt/*/*
// @match        https://*.ocregister.com/*/*
// @match        https://*.oglobo.globo.com/*/*
// @match        https://*.oregonlive.com/*/*
// @match        https://*.orlandosentinel.com/*/*
// @match        https://*.ostsee-zeitung.de/*/*
// @match        https://*.otz.de/*/*
// @match        https://*.outlookindia.com/*/*
// @match        https://*.outsideonline.com/*/*
// @match        https://*.oxygenmag.com/*/*
// @match        https://*.paloaltoonline.com/*/*
// @match        https://*.paris-normandie.fr/*/*
// @match        https://*.parismatch.com/*/*
// @match        https://*.parool.nl/*/*
// @match        https://*.pe.com/*/*
// @match        https://*.pelotonmagazine.com/*/*
// @match        https://*.pennlive.com/*/*
// @match        https://*.petitbleu.fr/*/*
// @match        https://*.philosophynow.org/*/*
// @match        https://*.pilotonline.com/*/*
// @match        https://*.piqd.de/*/*
// @match        https://*.podiumrunner.com/*/*
// @match        https://*.politicaexterior.com/*/*
// @match        https://*.popularmechanics.com/*/*
// @match        https://*.post-gazette.com/*/*
// @match        https://*.precisiononcologynews.com/*/*
// @match        https://*.prevention.com/*/*
// @match        https://*.prospectmagazine.co.uk/*/*
// @match        https://*.puck.news/*/*
// @match        https://*.quora.com/*/*
// @match        https://*.quotidiani.gelocal.it/*/*
// @match        https://*.quotidiano.net/*/*
// @match        https://*.quotidianodipuglia.it/*/*
// @match        https://*.qz.com/*/*
// @match        https://*.rechargenews.com/*/*
// @match        https://*.repubblica.it/*/*
// @match        https://*.republicain-lorrain.fr/*/*
// @match        https://*.reuters.com/*/*
// @match        https://*.rhein-zeitung.de/*/*
// @match        https://*.rheinpfalz.de/*/*
// @match        https://*.richmond.com/*/*
// @match        https://*.rnd.de/*/*
// @match        https://*.roadandtrack.com/*/*
// @match        https://*.rockandice.com/*/*
// @match        https://*.rollingstone.com/*/*
// @match        https://*.rugbypass.com/*/*
// @match        https://*.rundschau-online.de/*/*
// @match        https://*.runnersworld.com/*/*
// @match        https://*.sacbee.com/*/*
// @match        https://*.sandiegouniontribune.com/*/*
// @match        https://*.science-et-vie.com/*/*
// @match        https://*.science.org/*/*
// @match        https://*.sciencesetavenir.fr/*/*
// @match        https://*.scientificamerican.com/*/*
// @match        https://*.scmp.com/*/*
// @match        https://*.seattletimes.com/*/*
// @match        https://*.seekingalpha.com/*/*
// @match        https://*.sfchronicle.com/*/*
// @match        https://*.shz.de/*/*
// @match        https://*.si.com/*/*
// @match        https://*.silive.com/*/*
// @match        https://*.skimag.com/*/*
// @match        https://*.slate.com/*/*
// @match        https://*.slideshare.net/*/*
// @match        https://*.sloanreview.mit.edu/*/*
// @match        https://*.smh.com.au/*/*
// @match        https://*.sofrep.com/*/*
// @match        https://*.spectator.co.uk/*/*
// @match        https://*.spectator.com.au/*/*
// @match        https://*.spectatorworld.com/*/*
// @match        https://*.spglobal.com/*/*
// @match        https://*.sportico.com/*/*
// @match        https://*.standard.net.au/*/*
// @match        https://*.star-telegram.com/*/*
// @match        https://*.staradvertiser.com/*/*
// @match        https://*.startribune.com/*/*
// @match        https://*.statesman.com/*/*
// @match        https://*.statista.com/*/*
// @match        https://*.stcatharinesstandard.ca/*/*
// @match        https://*.stocknews.com/*/*
// @match        https://*.stratfor.com/*/*
// @match        https://*.study.com/*/*
// @match        https://*.sudinfo.be/*/*
// @match        https://*.sudouest.fr/*/*
// @match        https://*.sun-sentinel.com/*/*
// @match        https://*.svz.de/*/*
// @match        https://*.syracuse.com/*/*
// @match        https://*.talouselama.fi/*/*
// @match        https://*.tampabay.com/*/*
// @match        https://*.techinasia.com/*/*
// @match        https://*.technologyreview.com/*/*
// @match        https://*.tekniikkatalous.fi/*/*
// @match        https://*.telegraaf.nl/*/*
// @match        https://*.telegraph.co.uk/*/*
// @match        https://*.telerama.fr/*/*
// @match        https://*.the-american-interest.com/*/*
// @match        https://*.the-tls.co.uk/*/*
// @match        https://*.theadvocate.com.au/*/*
// @match        https://*.theadvocate.com/*/*
// @match        https://*.theage.com.au/*/*
// @match        https://*.theartnewspaper.com/*/*
// @match        https://*.theathletic.co.uk/*/*
// @match        https://*.theathletic.com/*/*
// @match        https://*.theatlantic.com/*/*
// @match        https://*.theaustralian.com.au/*/*
// @match        https://*.thechronicle.com.au/*/*
// @match        https://*.thecourier.com.au/*/*
// @match        https://*.thecut.com/*/*
// @match        https://*.thedailybeast.com/*/*
// @match        https://*.thediplomat.com/*/*
// @match        https://*.theglobeandmail.com/*/*
// @match        https://*.thehindu.com/*/*
// @match        https://*.thehindubusinessline.com/*/*
// @match        https://*.theintercept.com/*/*
// @match        https://*.thelawyersdaily.ca/*/*
// @match        https://*.themarker.com/*/*
// @match        https://*.themarket.ch/*/*
// @match        https://*.themercury.com.au/*/*
// @match        https://*.thenation.com/*/*
// @match        https://*.thenewatlantis.com/*/*
// @match        https://*.thepeterboroughexaminer.com/*/*
// @match        https://*.thepointmag.com/*/*
// @match        https://*.theprovince.com/*/*
// @match        https://*.therecord.com/*/*
// @match        https://*.thesaturdaypaper.com.au/*/*
// @match        https://*.thespec.com/*/*
// @match        https://*.thestar.com.my/*/*
// @match        https://*.thestar.com/*/*
// @match        https://*.thestate.com/*/*
// @match        https://*.thetimes.co.uk/*/*
// @match        https://*.thewest.com.au/*/*
// @match        https://*.thewrap.com/*/*
// @match        https://*.thueringer-allgemeine.de/*/*
// @match        https://*.tijd.be/*/*
// @match        https://*.time.com/*/*
// @match        https://*.timeshighereducation.com/*/*
// @match        https://*.timesofindia.indiatimes.com/*/*
// @match        https://*.tivi.fi/*/*
// @match        https://*.tlz.de/*/*
// @match        https://*.torontosun.com/*/*
// @match        https://*.towardsdatascience.com/*/*
// @match        https://*.townandcountrymag.com/*/*
// @match        https://*.townsvillebulletin.com.au/*/*
// @match        https://*.tradewindsnews.com/*/*
// @match        https://*.trailrunnermag.com/*/*
// @match        https://*.tri-cityherald.com/*/*
// @match        https://*.triathlete.com/*/*
// @match        https://*.trouw.nl/*/*
// @match        https://*.tucson.com/*/*
// @match        https://*.tulsaworld.com/*/*
// @match        https://*.twincities.com/*/*
// @match        https://*.unherd.com/*/*
// @match        https://*.upstreamonline.com/*/*
// @match        https://*.usatoday.com/*/*
// @match        https://*.usinenouvelle.com/*/*
// @match        https://*.uusisuomi.fi/*/*
// @match        https://*.valeursactuelles.com/*/*
// @match        https://*.valor.globo.com/*/*
// @match        https://*.vancouversun.com/*/*
// @match        https://*.vanityfair.com/*/*
// @match        https://*.variety.com/*/*
// @match        https://*.varmatin.com/*/*
// @match        https://*.vegetariantimes.com/*/*
// @match        https://*.velonews.com/*/*
// @match        https://*.venturebeat.com/*/*
// @match        https://*.vogue.com/*/*
// @match        https://*.voguebusiness.com/*/*
// @match        https://*.volkskrant.nl/*/*
// @match        https://*.volksstimme.de/*/*
// @match        https://*.vosgesmatin.fr/*/*
// @match        https://*.vulture.com/*/*
// @match        https://*.washingtonpost.com/*/*
// @match        https://*.watoday.com.au/*/*
// @match        https://*.waz.de/*/*
// @match        https://*.weeklytimesnow.com.au/*/*
// @match        https://*.wellandtribune.ca/*/*
// @match        https://*.westernadvocate.com.au/*/*
// @match        https://*.westfalen-blatt.de/*/*
// @match        https://*.winnipegfreepress.com/*/*
// @match        https://*.wired.com/*/*
// @match        https://*.wn.de/*/*
// @match        https://*.womenshealthmag.com/*/*
// @match        https://*.womensrunning.com/*/*
// @match        https://*.worldpoliticsreview.com/*/*
// @match        https://*.wp.de/*/*
// @match        https://*.wr.de/*/*
// @match        https://*.wsj.com/*/*
// @match        https://*.wwd.com/*/*
// @match        https://*.wz.de/*/*
// @match        https://*.yogajournal.com/*/*
// @match        https://*.zeit.de/*/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    window.location.replace(`https://www.removepaywall.com/search?url=${encodeURIComponent(window.location.href)}`);
})();
